"""Assemble monolithic skill files for Copilot and Windsurf."""

from pathlib import Path

from .rewriter import rewrite_references

ASSEMBLY_HEADER = "<!-- GENERATED by build_skills.py — do not edit directly -->\n\n"
STATIC_INTRO = (
    "This document contains the complete set of guardrails and skills "
    "that apply to this project. Each section below is a generated skill. "
    "Do not edit this file directly; run `python scripts/build_skills.py` to regenerate."
)
STATIC_FOOTER = (
    "- [Agent Guardrails](docs/AGENT_GUARDRAILS.md)\n"
    "- [Project Guidelines](CLAUDE.md)"
)

SKILL_ORDER = [
    "guardrails-enforcer",
    "four-laws",
    "halt-conditions",
    "three-strikes",
    "production-first",
    "scope-validator",
    "commit-validator",
    "env-separator",
    "error-recovery",
    "3d-game-dev",
    "vibe-coding",
]


def _skill_sort_key(skill) -> tuple:
    """Deterministic sort key for monolithic assembly ordering."""
    try:
        return (SKILL_ORDER.index(skill.id), skill.id)
    except ValueError:
        return (len(SKILL_ORDER), skill.id)


def assemble_content(skills, platform: str) -> str:
    """Assemble a monolithic markdown file for Copilot or Windsurf.

    Args:
        skills: List of Skill dataclasses.
        platform: Either "copilot" or "windsurf".

    Returns:
        The assembled markdown content as a string.
    """
    applicable = [s for s in skills if platform in s.applies_to]
    applicable.sort(key=_skill_sort_key)

    lines = [ASSEMBLY_HEADER.rstrip()]
    lines.append("")
    lines.append(STATIC_INTRO)
    lines.append("")
    lines.append("## Table of Contents")
    for skill in applicable:
        lines.append(f"- [{skill.name}](#{skill.id})")
    lines.append("")

    for skill in applicable:
        body = rewrite_references(skill.body, platform)
        lines.append(f"## {skill.name}")
        lines.append(f'<a id="{skill.id}"></a>')
        lines.append("")
        lines.append(body)
        lines.append("")
        lines.append("---")
        lines.append("")

    lines.append("## References")
    lines.append("")
    lines.append(STATIC_FOOTER)
    lines.append("")

    return "\n".join(lines)


def generate_copilot(skills, out_path: str | Path) -> None:
    """Generate `.github/copilot-instructions.md`."""
    path = Path(out_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(assemble_content(skills, "copilot"), encoding="utf-8")


def generate_windsurf(skills, out_path: str | Path) -> None:
    """Generate `.windsurfrules`."""
    path = Path(out_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(assemble_content(skills, "windsurf"), encoding="utf-8")
