"""Generate per-platform native skill files."""

import json
from pathlib import Path

from .rewriter import rewrite_references

CLAUDE_HEADER = "# GENERATED by build_skills.py — do not edit directly\n\n"
CURSOR_HEADER = "<!-- GENERATED by build_skills.py — do not edit directly -->\n\n"
OC_HEADER = "<!-- GENERATED by build_skills.py — do not edit directly -->\n\n"


def _write(path: Path, content: str) -> None:
    """Ensure parent directories exist and write content."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def claude_content(skill) -> str:
    """Return the JSON content for a Claude Code skill file."""
    body = rewrite_references(skill.body, "claude")
    data = {
        "name": skill.id,
        "description": skill.description,
        "tools": skill.tools or [],
        "prompt": CLAUDE_HEADER + body,
    }
    return json.dumps(data, indent=2) + "\n"


def generate_claude(skills, out_dir: str | Path) -> None:
    """Generate `.claude/skills/<id>.json` files."""
    for skill in skills:
        if "claude" not in skill.applies_to:
            continue
        path = Path(out_dir) / ".claude" / "skills" / f"{skill.id}.json"
        _write(path, claude_content(skill))


def _strip_leading_h1(body: str, name: str) -> str:
    """Remove the first H1 if it matches the skill name to avoid duplicates."""
    lines = body.splitlines()
    if lines and lines[0].strip() == f"# {name}":
        lines = lines[1:]
        # Strip leading blank lines
        while lines and lines[0].strip() == "":
            lines = lines[1:]
        return "\n".join(lines)
    return body


def cursor_content(skill) -> str:
    """Return the markdown content for a Cursor rules file."""
    body = rewrite_references(skill.body, "cursor")
    body = _strip_leading_h1(body, skill.name)
    lines = [
        CURSOR_HEADER.rstrip(),
        "---",
        f"description: {skill.description}",
        f'globs: "{skill.globs or "**/*"}"',
        f"alwaysApply: {str(skill.alwaysApply).lower()}",
        "---",
        "",
        f"# {skill.name}",
        "",
        body,
        "",
    ]
    return "\n".join(lines)


def generate_cursor(skills, out_dir: str | Path) -> None:
    """Generate `.cursor/rules/<id>.md` files."""
    for skill in skills:
        if "cursor" not in skill.applies_to:
            continue
        path = Path(out_dir) / ".cursor" / "rules" / f"{skill.id}.md"
        _write(path, cursor_content(skill))


def oc_content(skill, platform: str) -> str:
    """Return the markdown content for an OpenCode or OpenClaw SKILL.md file."""
    body = rewrite_references(skill.body, platform)
    body = _strip_leading_h1(body, skill.name)
    lines = [
        OC_HEADER.rstrip(),
        "---",
        f"name: {skill.id}",
        f'description: "{skill.description}"',
        "---",
        "",
        f"# {skill.name}",
        "",
        body,
        "",
    ]
    return "\n".join(lines)


def generate_opencode(skills, out_dir: str | Path) -> None:
    """Generate `.opencode/skills/<id>/SKILL.md` files."""
    for skill in skills:
        if "opencode" not in skill.applies_to:
            continue
        path = Path(out_dir) / ".opencode" / "skills" / skill.id / "SKILL.md"
        _write(path, oc_content(skill, "opencode"))


def generate_openclaw(skills, out_dir: str | Path) -> None:
    """Generate `.openclaw/skills/<id>/SKILL.md` files."""
    for skill in skills:
        if "openclaw" not in skill.applies_to:
            continue
        path = Path(out_dir) / ".openclaw" / "skills" / skill.id / "SKILL.md"
        _write(path, oc_content(skill, "openclaw"))
