#!/usr/bin/env python3
"""
Vision Pipeline Setup Wizard

Interactively configures the MCP server's vision pipeline by asking:
1. Do you have a local model (llama-server)?
2. If not, do you have a network endpoint?
3. If neither, configure a fallback provider (Anthropic/OpenAI).

Usage:
    python scripts/setup_vision_wizard.py
"""

import os
import sys
from pathlib import Path


def ask_yes_no(question: str, default: bool = False) -> bool:
    """Prompt user for a yes/no answer."""
    suffix = " [Y/n]: " if default else " [y/N]: "
    response = input(question + suffix).strip().lower()
    if not response:
        return default
    return response in ("y", "yes")


def ask_input(question: str, default: str = "") -> str:
    """Prompt user for text input with an optional default."""
    if default:
        prompt = f"{question} [{default}]: "
    else:
        prompt = f"{question}: "
    response = input(prompt).strip()
    return response if response else default


def ask_choice(question: str, choices: list[str], default: str = None) -> str:
    """Prompt user to choose from a list."""
    print(question)
    for i, choice in enumerate(choices, 1):
        marker = " (default)" if choice == default else ""
        print(f"  {i}. {choice}{marker}")
    response = input("Enter number or name: ").strip()
    if not response and default:
        return default
    if response.isdigit():
        idx = int(response) - 1
        if 0 <= idx < len(choices):
            return choices[idx]
    for choice in choices:
        if choice.lower() == response.lower():
            return choice
    print(f"Invalid choice '{response}'. Using default '{default}'.")
    return default


def write_config(config_path: Path, content: str) -> None:
    """Write configuration file and print summary."""
    config_path.parent.mkdir(parents=True, exist_ok=True)
    with open(config_path, "w") as f:
        f.write(content)
    print(f"\n[OK] Configuration written to: {config_path}")


def build_config(
    local_url: str = "",
    local_model: str = "",
    remote_url: str = "",
    remote_api_key: str = "",
    remote_model: str = "",
    fallback_provider: str = "anthropic",
    fallback_model: str = "",
    fallback_api_key: str = "",
    fallback_url: str = "",
) -> str:
    """Build the vision.yaml content.

    Note: The Go MCP server only reads LOCAL_LLAMA_URL (local_url) as the
    primary endpoint. Network/remote endpoints are placed in local_url so
    the server actually uses them. remote_url is kept for documentation.
    """
    # Determine effective primary URL (local takes precedence, then remote)
    primary_url = local_url or remote_url
    primary_model = local_model or remote_model

    lines = [
        "# Vision Pipeline Configuration",
        "# Generated by setup_vision_wizard.py",
        "",
        "inference:",
    ]

    if primary_url:
        lines.extend([
            f'  # Primary endpoint (LOCAL_LLAMA_URL env var)',
            f'  # Note: "local" here means "primary" in the Go code — it can be a network endpoint',
            f'  local_url: "{primary_url}"',
            f'  local_model: "{primary_model}"',
        ])
    else:
        lines.extend([
            '  # Primary endpoint (empty — only fallback will be used)',
            '  local_url: ""',
            '  local_model: ""',
        ])

    if remote_url and not local_url:
        lines.extend([
            f'  # Remote endpoint documentation (also set in LOCAL_LLAMA_URL above)',
            f'  remote_url: "{remote_url}"',
            f'  remote_model: "{remote_model}"',
            f'  remote_api_key: "{remote_api_key}"',
        ])

    if fallback_url:
        lines.append(f'  fallback_url: "{fallback_url}"')

    lines.extend([
        f'  fallback_provider: "{fallback_provider}"',
        f'  fallback_model: "{fallback_model}"',
        f'  fallback_api_key: "{fallback_api_key}"',
        "  fallback_max_tokens: 4096",
        "",
        "  # llama-server tuning (for documentation/reference)",
        '  mmproj_path: "/mnt/data/models/nemotron-30b-a3b/mmproj-F16.gguf"',
        "  context_size: 120000",
        '  kv_cache_quantization: "q4_1"',
        "  flash_attention: true",
        "",
        "capture:",
        '  watch_dir: "${SCREENSHOT_DIR}"',
        "  auto_review: true",
        "  trigger_interval_seconds: 30",
        "",
        "review:",
        "  max_iterations: 3",
        "  confidence_threshold: 0.75",
        "  system_prompt: |",
        "    You are a 3D game QA engineer. Analyze the provided screenshot and report",
        "    issues related to visual quality, performance, and adherence to game",
        "    design standards. Output findings as a JSON array with fields:",
        "    category, severity (info/warning/critical), description.",
        "  fallback_prompt: |",
        "    Re-examine this image focusing on any issues you may have missed.",
        "    Be specific about visual artifacts, lighting problems, UI inconsistencies,",
        "    or performance indicators.",
    ])

    return "\n".join(lines) + "\n"


def update_env_file(env_path: Path, updates: dict[str, str]) -> None:
    """Update or append key=value lines in the .env file."""
    if not env_path.exists():
        print(f"[WARN] {env_path} not found. Skipping .env update.")
        print("         Create it from .env.example and re-run this wizard.")
        return

    content = env_path.read_text()
    lines = content.splitlines()
    seen = set()
    new_lines = []

    for line in lines:
        stripped = line.strip()
        if stripped.startswith("#") or "=" not in stripped:
            new_lines.append(line)
            continue
        key = stripped.split("=", 1)[0]
        if key in updates:
            new_lines.append(f"{key}={updates[key]}")
            seen.add(key)
        else:
            new_lines.append(line)

    for key, value in updates.items():
        if key not in seen:
            new_lines.append(f"{key}={value}")

    env_path.write_text("\n".join(new_lines) + "\n")
    print(f"[OK] Updated {env_path}")


def main() -> int:
    print("=" * 60)
    print("  Vision Pipeline Setup Wizard")
    print("=" * 60)
    print()
    print("This wizard configures the MCP server's vision inference pipeline.")
    print("It will ask about your available model backends and generate")
    print("the appropriate configuration file.")
    print()

    # Determine output path
    repo_root = Path.cwd()
    while repo_root != repo_root.parent:
        if (repo_root / "mcp-server").exists():
            break
        repo_root = repo_root.parent
    else:
        print("[ERR] Could not find mcp-server directory.")
        return 1

    config_path = repo_root / "mcp-server" / "vision.yaml"

    local_url = ""
    local_model = ""
    remote_url = ""
    remote_api_key = ""
    remote_model = ""
    fallback_url = ""

    # Step 1: Local model
    has_local = ask_yes_no("Do you have a local llama-server (or compatible local model) running?")
    if has_local:
        local_url = ask_input("Local model endpoint URL", "http://localhost:8080/v1")
        local_model = ask_input("Local model name", "nemotron-vision-local")
        print(f"\n[INFO] Local model configured: {local_url}")
    else:
        print("\n[INFO] No local model selected.")

    # Step 2: Network endpoint
    has_remote = False
    if not has_local:
        has_remote = ask_yes_no("Do you have a remote/network endpoint (e.g., another machine running llama-server)?")
        if has_remote:
            remote_url = ask_input("Remote endpoint URL")
            remote_model = ask_input("Remote model name", "nemotron-vision-remote")
            remote_api_key = ask_input("Remote API key (if required, or leave blank)")
            print(f"\n[INFO] Remote endpoint configured: {remote_url}")
        else:
            print("\n[INFO] No remote endpoint selected.")

    # Step 3: Fallback provider (always required as a safety net)
    print()
    print("A fallback provider is required for when local/remote models are unavailable.")
    fallback_provider = ask_choice(
        "Choose fallback provider:",
        ["anthropic", "openai", "custom"],
        default="anthropic",
    )

    if fallback_provider == "anthropic":
        fallback_model_default = "claude-3-5-sonnet"
    elif fallback_provider == "openai":
        fallback_model_default = "gpt-4o"
    else:
        fallback_model_default = "custom-model"

    fallback_model = ask_input("Fallback model name", fallback_model_default)

    if fallback_provider == "custom":
        fallback_url = ask_input("Custom fallback endpoint URL")

    fallback_api_key = ask_input("Fallback API key")

    if not fallback_api_key:
        print("[WARN] No fallback API key provided. The fallback will not work until you set one.")

    # Write configuration
    config_content = build_config(
        local_url=local_url,
        local_model=local_model,
        remote_url=remote_url,
        remote_api_key=remote_api_key,
        remote_model=remote_model,
        fallback_provider=fallback_provider,
        fallback_model=fallback_model,
        fallback_api_key=fallback_api_key,
        fallback_url=fallback_url,
    )

    write_config(config_path, config_content)

    # Update .env with vision variables so the Go server actually reads them
    env_path = repo_root / "mcp-server" / ".env"
    primary_url = local_url or remote_url
    primary_model = local_model or remote_model
    env_updates = {
        "VISION_ENABLED": "true",
        "LOCAL_LLAMA_URL": primary_url or "",
        "LOCAL_LLAMA_MODEL": primary_model or "",
        "FALLBACK_PROVIDER": fallback_provider,
        "FALLBACK_MODEL": fallback_model,
        "FALLBACK_API_KEY": fallback_api_key,
        "FALLBACK_URL": fallback_url or "",
    }
    update_env_file(env_path, env_updates)

    print("\nNext steps:")
    if primary_url:
        print(f"  - Ensure your model endpoint is running at: {primary_url}")
    if fallback_url:
        print(f"  - Ensure your custom fallback endpoint is accessible: {fallback_url}")
    if not fallback_api_key:
        print(f"  - Set your fallback API key as an environment variable:")
        print(f"      FALLBACK_API_KEY=your_key_here")
    print(f"  - Review the full configuration in: {config_path}")
    print()
    print("[OK] Wizard complete!")

    return 0


if __name__ == "__main__":
    sys.exit(main())
