"""Tests for skill_lib/generator.py."""

import json
from pathlib import Path

import pytest

from skill_lib.generator import (
    claude_content,
    cursor_content,
    generate_claude,
    generate_cursor,
    generate_openclaw,
    generate_opencode,
    oc_content,
)


class TestClaudeContent:
    def test_json_structure(self, sample_skill):
        content = claude_content(sample_skill)
        data = json.loads(content)
        assert data["name"] == "test-skill"
        assert data["description"] == "A skill for testing."
        assert data["tools"] == ["Read", "Grep"]
        assert "# GENERATED by build_skills.py" in data["prompt"]
        assert "Some instructions." in data["prompt"]

    def test_empty_tools_list_when_none(self, minimal_skill):
        minimal_skill.tools = None
        content = claude_content(minimal_skill)
        data = json.loads(content)
        assert data["tools"] == []

    def test_references_rewritten(self, sample_skill):
        content = claude_content(sample_skill)
        data = json.loads(content)
        assert "skills/shared-prompts/other.md" in data["prompt"]
        assert "skills/other/SKILL.md" not in data["prompt"]


class TestCursorContent:
    def test_markdown_structure(self, sample_skill):
        content = cursor_content(sample_skill)
        assert "<!-- GENERATED by build_skills.py" in content
        assert "description: A skill for testing." in content
        assert 'globs: "**/*.py"' in content
        assert "alwaysApply: true" in content
        assert "# Test Skill" in content
        assert "Some instructions." in content

    def test_strips_duplicate_h1(self, sample_skill):
        sample_skill.body = "# Test Skill\n\nSome instructions.\n"
        content = cursor_content(sample_skill)
        lines = content.splitlines()
        h1_lines = [l for l in lines if l == "# Test Skill"]
        assert len(h1_lines) == 1

    def test_default_globs(self, minimal_skill):
        minimal_skill.globs = None
        content = cursor_content(minimal_skill)
        assert 'globs: "**/*"' in content


class TestOCContent:
    def test_opencode_structure(self, sample_skill):
        content = oc_content(sample_skill, "opencode")
        assert "<!-- GENERATED by build_skills.py" in content
        assert "name: test-skill" in content
        assert 'description: "A skill for testing."' in content
        assert "# Test Skill" in content

    def test_openclaw_structure(self, sample_skill):
        content = oc_content(sample_skill, "openclaw")
        assert "name: test-skill" in content

    def test_strips_duplicate_h1(self, sample_skill):
        sample_skill.body = "# Test Skill\n\nInstructions.\n"
        content = oc_content(sample_skill, "opencode")
        lines = content.splitlines()
        h1_lines = [l for l in lines if l == "# Test Skill"]
        assert len(h1_lines) == 1


class TestGenerateClaude:
    def test_skips_non_claude_skills(self, tmp_path, minimal_skill):
        minimal_skill.applies_to = ["cursor"]
        generate_claude([minimal_skill], tmp_path)
        assert not list(tmp_path.rglob("*.json"))

    def test_generates_file(self, tmp_path, minimal_skill):
        minimal_skill.applies_to = ["claude"]
        generate_claude([minimal_skill], tmp_path)
        path = tmp_path / ".claude" / "skills" / "minimal.json"
        assert path.exists()
        data = json.loads(path.read_text())
        assert data["name"] == "minimal"


class TestGenerateCursor:
    def test_skips_non_cursor_skills(self, tmp_path, minimal_skill):
        minimal_skill.applies_to = ["claude"]
        generate_cursor([minimal_skill], tmp_path)
        assert not list(tmp_path.rglob("*.md"))

    def test_generates_file(self, tmp_path, minimal_skill):
        minimal_skill.applies_to = ["cursor"]
        generate_cursor([minimal_skill], tmp_path)
        path = tmp_path / ".cursor" / "rules" / "minimal.md"
        assert path.exists()
        assert "# Minimal" in path.read_text()


class TestGenerateOpencode:
    def test_generates_nested_file(self, tmp_path, minimal_skill):
        minimal_skill.applies_to = ["opencode"]
        generate_opencode([minimal_skill], tmp_path)
        path = tmp_path / ".opencode" / "skills" / "minimal" / "SKILL.md"
        assert path.exists()
        assert "name: minimal" in path.read_text()


class TestGenerateOpenclaw:
    def test_generates_nested_file(self, tmp_path, minimal_skill):
        minimal_skill.applies_to = ["openclaw"]
        generate_openclaw([minimal_skill], tmp_path)
        path = tmp_path / ".openclaw" / "skills" / "minimal" / "SKILL.md"
        assert path.exists()
