"""Tests for skill_lib/assembler.py."""

from skill_lib.assembler import (
    SKILL_ORDER,
    _skill_sort_key,
    assemble_content,
    generate_copilot,
    generate_windsurf,
)
from skill_lib.parser import Skill


class TestSkillSortKey:
    def test_ordered_skills_sort_first(self):
        s = Skill(id="four-laws", name="Four Laws", description="d", version="1", applies_to=["x"], body="b")
        assert _skill_sort_key(s) == (1, "four-laws")

    def test_unknown_skills_sort_last(self):
        s = Skill(id="unknown", name="Unknown", description="d", version="1", applies_to=["x"], body="b")
        assert _skill_sort_key(s) == (len(SKILL_ORDER), "unknown")

    def test_deterministic_ordering(self):
        s1 = Skill(id="guardrails-enforcer", name="G", description="d", version="1", applies_to=["x"], body="b")
        s2 = Skill(id="four-laws", name="F", description="d", version="1", applies_to=["x"], body="b")
        assert _skill_sort_key(s1) < _skill_sort_key(s2)


class TestAssembleContent:
    def test_includes_toc(self, minimal_skill):
        minimal_skill.applies_to = ["copilot"]
        content = assemble_content([minimal_skill], "copilot")
        assert "## Table of Contents" in content
        assert "- [Minimal](#minimal)" in content

    def test_includes_skill_section(self, minimal_skill):
        minimal_skill.applies_to = ["copilot"]
        minimal_skill.body = "Do the thing."
        content = assemble_content([minimal_skill], "copilot")
        assert "## Minimal" in content
        assert '<a id="minimal"></a>' in content
        assert "Do the thing." in content

    def test_skips_non_applicable_skills(self):
        s = Skill(id="x", name="X", description="d", version="1", applies_to=["claude"], body="b")
        content = assemble_content([s], "copilot")
        assert "## X" not in content

    def test_rewrites_references_for_monolithic(self):
        s = Skill(
            id="four-laws",
            name="Four Laws",
            description="d",
            version="1",
            applies_to=["copilot"],
            body="See skills/halt-conditions/SKILL.md.",
        )
        content = assemble_content([s], "copilot")
        assert "#halt-conditions" in content
        assert "skills/halt-conditions/SKILL.md" not in content

    def test_generates_header_and_footer(self, minimal_skill):
        minimal_skill.applies_to = ["copilot"]
        content = assemble_content([minimal_skill], "copilot")
        assert "<!-- GENERATED by build_skills.py" in content
        assert "## References" in content

    def test_same_content_for_windsurf_and_copilot(self, minimal_skill):
        minimal_skill.applies_to = ["copilot", "windsurf"]
        copilot = assemble_content([minimal_skill], "copilot")
        windsurf = assemble_content([minimal_skill], "windsurf")
        assert copilot == windsurf

    def test_skills_sorted_by_skill_order(self):
        s1 = Skill(id="vibe-coding", name="Vibe", description="d", version="1", applies_to=["copilot"], body="b")
        s2 = Skill(id="four-laws", name="Four", description="d", version="1", applies_to=["copilot"], body="b")
        content = assemble_content([s1, s2], "copilot")
        four_pos = content.index("## Four")
        vibe_pos = content.index("## Vibe")
        assert four_pos < vibe_pos


class TestGenerateCopilot:
    def test_writes_file(self, tmp_path, minimal_skill):
        minimal_skill.applies_to = ["copilot"]
        out = tmp_path / "copilot-instructions.md"
        generate_copilot([minimal_skill], out)
        assert out.exists()
        assert "## Minimal" in out.read_text()


class TestGenerateWindsurf:
    def test_writes_file(self, tmp_path, minimal_skill):
        minimal_skill.applies_to = ["windsurf"]
        out = tmp_path / ".windsurfrules"
        generate_windsurf([minimal_skill], out)
        assert out.exists()
        assert "## Minimal" in out.read_text()
